
name: Push to Dockerhub

on:
  push:
    tags:
      - '*'

jobs:
  build:
    if: ${{ github.head_ref }} == "master"
    runs-on: ubuntu-latest
    environment: dockerhub
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Build and Test
      run: |
        yarn
        yarn test
        yarn build
    - name: Build Docker
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.LIFEOMIC_DOCKERHUB_USERNAME }}
        password: ${{ secrets.LIFEOMIC_DOCKERHUB_TOKEN }}
        repository: lifeomic/ashion-ingest
        tag_with_ref: true
        push: ${{ startsWith(github.ref, 'refs/tags/') }}
    - name: Create Release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: false
        prerelease: false